name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <accound>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      # run: | curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose chmod +x /usr/local/bin/docker-compose
      # run: docker compose build --no-cache --force-rm
      run: |
        docker build "$GITHUB_WORKSPACE" -t ${{ secrets.DOCKER_USERNAME }}/angulartutorial:$GITHUB_SHA --label dockerfile-path="Dockerfile"

  test:
    runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v2
    # - name: Test the Docker image
    #   run: docker compose up -d
    # new:
    steps:
      - name: test
        run: |
          docker compose up -d

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps: 
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: "{{defaultContext}}"
    #     push: true
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}

    - name: Build Docker image
      id: build_image
      run: |
        docker build "$GITHUB_WORKSPACE" -t ${{ secrets.DOCKER_USERNAME }}/angulartutorial:$GITHUB_SHA --label dockerfile-path="Dockerfile"

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/angulartutorial:$GITHUB_SHA

    - name: Logout from Docker Hub
      run: docker logout

    - name: End
      run: echo "Docker image pushed to Docker Hub successfully"